# -*- coding: utf-8 -*-
"""Assignment3_q2_SMF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mq3ljkvoX0fAsRTNlMy41ZWSm2NLVP31

# Question 2: Itô’s Lemma and Geometric Brownian Motion

## part (d)
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import lognorm

# Parameters
S0 = 100
mu = 0.07
sigma = 0.2
T = 1
N = 500
M = 50000

dt = T / N

# Simulate paths using Euler-Maruyama
S = np.full(M, S0, dtype=float)

for _ in range(N):
    Z = np.random.randn(M)
    S += mu * S * dt + sigma * S * np.sqrt(dt) * Z

ST = S

# Histogram
plt.hist(ST, bins=100, density=True, alpha=0.6,
         label='Simulated')

# Theoretical lognormal density
x = np.linspace(min(ST), max(ST), 1000)

shape = sigma * np.sqrt(T)
scale = S0 * np.exp((mu - 0.5 * sigma**2) * T)

pdf = lognorm.pdf(x, s=shape, scale=scale)

plt.plot(x, pdf, 'r', lw=2,
         label='Theoretical Lognormal')

plt.xlabel('Terminal Stock Price')
plt.ylabel('Density')
plt.title('Distribution of $S_T$')
plt.legend()
plt.show()

"""##Observation

The simulated histogram closely matches the theoretical log-normal density. The distribution is positively skewed with a long right tail, which is characteristic of Geometric Brownian Motion. Small discrepancies are due to simulation error and finite sample size.

## part (e)
"""

# Empirical values
emp_mean = np.mean(ST)
emp_std = np.std(ST)

# Theoretical values
theo_mean = S0 * np.exp(mu * T)

theo_std = S0 * np.exp(mu * T) * \
           np.sqrt(np.exp(sigma**2 * T) - 1)

print("Empirical Mean =", emp_mean)
print("Theoretical Mean =", theo_mean)

print("Empirical Std =", emp_std)
print("Theoretical Std =", theo_std)

"""Observation

The empirical mean and standard deviation are very close to their theoretical values. This confirms that the Euler-Maruyama simulation accurately reproduces the statistical properties of the Geometric Brownian Motion model.

## Part (f)
"""

sigmas = [0.1, 0.3, 0.5]

for sigma in sigmas:

    S = np.full(M, S0, dtype=float)

    for _ in range(N):
        Z = np.random.randn(M)
        S += mu * S * dt + sigma * S * np.sqrt(dt) * Z

    ST = S

    mean_ST = np.mean(ST)
    std_ST = np.std(ST)

    payoff = np.mean(np.maximum(ST - 110, 0))

    print("\nSigma =", sigma)
    print("Mean(ST) =", mean_ST)
    print("Std(ST) =", std_ST)
    print("E[(ST-110)+] =", payoff)

"""Observation

As volatility increases, the distribution of terminal stock prices becomes wider and more dispersed. The expected stock price remains nearly unchanged, but the standard deviation increases significantly.

The expected call option payoff E[(ST−110)+] also increases with volatility because larger fluctuations create a greater probability of ending above the strike price.

## Part (g)
"""

# Log returns
log_returns = np.log(ST / S0)

emp_mean = np.mean(log_returns)
emp_var = np.var(log_returns)

theo_mean = (mu - 0.5 * sigma**2) * T
theo_var = sigma**2 * T

print("Empirical Mean =", emp_mean)
print("Theoretical Mean =", theo_mean)

print("Empirical Variance =", emp_var)
print("Theoretical Variance =", theo_var)

plt.hist(log_returns,
         bins=100,
         density=True,
         alpha=0.7)

plt.title("Histogram of Log Returns")
plt.xlabel("Log Return")
plt.ylabel("Density")
plt.show()

"""The histogram of log-returns is approximately bell-shaped, indicating a normal distribution. The empirical mean and variance are close to (μ−σ2/2)T and σ2T, confirming the theoretical GBM model."""