# -*- coding: utf-8 -*-
"""Assignment3_q1_SMF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ndff3AXLBhjxhMrMSjO3BALliFKR6HMD

# Question 1 Brownian Motion Paths and Quadratic Variation

## Part(e)
"""

import numpy as np

N = 10000
dt = 1/N

dW = np.sqrt(dt)*np.random.randn(N)
W = np.concatenate(([0], np.cumsum(dW)))

QV = np.sum(dW**2)
TV = np.sum(np.abs(dW))

print("Quadratic variation =", QV)
print("Total variation =", TV)

"""## Part (f)"""

Ns = [10,50,100,500,1000,5000,10000]
qv = []

for N in Ns:
    dt = 1/N
    dW = np.sqrt(dt)*np.random.randn(N)
    qv.append(np.sum(dW**2))

"""## Part (g)"""

M = 10000
t = 0.5

samples = np.sqrt(t)*np.random.randn(M)

print(np.mean(samples))
print(np.var(samples))

"""Theoretical values:
E[W0.5​]=0,<br>
Var(W0.5)=0.5.
"""