# -*- coding: utf-8 -*-
"""Assignment3_q3_smf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnarGGJ3QQatvufwquGXX3EYRTcc-O9y

# Question 3: Euler–Maruyama Simulation and the Ornstein–Uhlenbeck Process

## part (d)
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
X0 = 3.0
theta = 2.0
sigma = 0.5

T = 5
N = 5000
M = 10

dt = T/N

t = np.linspace(0,T,N+1)

paths = np.zeros((M,N+1))
paths[:,0] = X0

for i in range(M):
    for k in range(N):
        Z = np.random.randn()

        paths[i,k+1] = (
            paths[i,k]
            - theta*paths[i,k]*dt
            + sigma*np.sqrt(dt)*Z
        )

# Plot paths
for i in range(M):
    plt.plot(t,paths[i])

# Stationary mean
plt.axhline(0,color='black',
            linestyle='--',
            label='Mean')

# ±2 std band
std_inf = sigma/np.sqrt(2*theta)

plt.fill_between(
    t,
    -2*std_inf,
    2*std_inf,
    alpha=0.2,
    label='±2σ band'
)

plt.xlabel("Time")
plt.ylabel("X(t)")
plt.legend()
plt.show()

"""All paths initially start from X0=3 and gradually move toward zero because of mean reversion. After some time, most paths fluctuate within the stationary band ±2σ/2θ.

## part (e)
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

X0 = 3
theta = 2
sigma = 0.5

T = 10
N = 10000
M = 20000

dt = T/N

X = np.full(M,X0,dtype=float)

for _ in range(N):

    Z = np.random.randn(M)

    X += -theta*X*dt \
         + sigma*np.sqrt(dt)*Z

XT = X

# Histogram
plt.hist(XT,
         bins=100,
         density=True,
         alpha=0.6)

# Theoretical density
x = np.linspace(min(XT),
                max(XT),
                1000)

var_theory = sigma**2/(2*theta)

pdf = norm.pdf(
        x,
        loc=0,
        scale=np.sqrt(var_theory)
      )

plt.plot(x,pdf,'r',lw=2)

plt.show()

# Statistics
print("Empirical Mean =",np.mean(XT))
print("Empirical Variance =",np.var(XT))

print("Theoretical Mean = 0")
print("Theoretical Variance =",var_theory)

"""The histogram closely matches the theoretical normal density. The empirical mean is close to zero and the empirical variance is close to 0.0625, confirming convergence to the stationary distribution.

## part (f)
"""

import numpy as np
import matplotlib.pyplot as plt

thetas = [0.5,2.0,5.0]

X0 = 3
sigma = 0.5

T = 5
N = 5000
dt = T/N

t = np.linspace(0,T,N+1)

fig,axs = plt.subplots(3,1,
                       figsize=(8,10))

for j,theta in enumerate(thetas):

    for i in range(10):

        X = np.zeros(N+1)
        X[0] = X0

        for k in range(N):

            Z = np.random.randn()

            X[k+1] = (
                X[k]
                - theta*X[k]*dt
                + sigma*np.sqrt(dt)*Z
            )

        axs[j].plot(t,X)

    axs[j].set_title(
        f"theta={theta}"
    )

plt.tight_layout()
plt.show()

"""Observation on Mean Reversion

As θ increases, the restoring force becomes stronger and paths return to zero more quickly. Small values of θ produce slow mean reversion, causing paths to wander farther from zero.

Observation on Stationary Distribution

Since, Var(X∞)=2θσ2,larger θ leads to a smaller variance and a narrower stationary distribution. Smaller θ produces a wider distribution with larger fluctuations around the mean.

## part (g)

The Euler–Maruyama method has strong convergence order 1/2 and weak convergence order 1.

Strong convergence means that the simulated path stays close to the actual path of the stochastic process. If we make the time step smaller, the simulated trajectory becomes closer to the true trajectory.

Weak convergence means that the averages calculated from the simulation are close to the true averages. Even if individual paths are not very accurate, quantities such as means, probabilities, and expected payoffs are estimated correctly.

Difference Between Them

Strong convergence is concerned with the accuracy of each individual path.

Weak convergence is concerned with the accuracy of statistical quantities obtained from many paths.

Why Weak Convergence is Enough for Option Pricing

In option pricing, we are usually interested in the expected payoff E[g(XT)],

for example, E[(XT−K)+].

We do not need every simulated path to match the true path exactly. We only need the average payoff over many paths to be accurate.

Therefore, weak convergence is sufficient for option pricing because it ensures that expected values computed from the simulation are close to the true expected values.

Conclusion

Strong convergence tells us how accurately individual sample paths are simulated, while weak convergence tells us how accurately averages are computed. Since option pricing depends on expected payoffs rather than exact paths, weak convergence is usually the more important property in Monte Carlo simulations.
"""