# -*- coding: utf-8 -*-
"""Stochastic maths for finance_Assignment1_Q1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E1wzvWmLhl6tlIJE8Z-QTgaDaFCcavwE

# Question 1 : Simulation part
"""

# using the joint distribution approach

import numpy as np

np.random.seed(42)

n = 10000

states = [
    (0, 0),
    (0, 1),
    (1, 0),
    (1, 1)
]

probs = [0.77, 0.13, 0.03, 0.07]

samples = np.random.choice(4, size=n, p=probs)

IA = np.array([states[i][0] for i in samples])
IB = np.array([states[i][1] for i in samples])

N = IA + IB

print("P(A∩B) =", np.mean((IA == 1) & (IB == 1)))
print("P(A∪B) =", np.mean((IA == 1) | (IB == 1)))
print("E[N]   =", np.mean(N))
print("Var(N) =", np.var(N))

# using the conditional- generation approach

import numpy as np

n = 10000

IA = np.zeros(n, dtype=int)
IB = np.zeros(n, dtype=int)

for i in range(n):

    # Generate LB
    IB[i] = np.random.rand() < 0.20

    # Generate LA conditionally
    if IB[i]:
        IA[i] = np.random.rand() < 0.35
    else:
        IA[i] = np.random.rand() < 0.0375

N = IA + IB

print("P(LA ∩ LB) =", np.mean((IA == 1) & (IB == 1)))
print("P(LA ∪ LB) =", np.mean((IA == 1) | (IB == 1)))
print("E[N] =", np.mean(N))
print("Var(N) =", np.var(N))

"""Approach 1: Compute the probabilities of all possible outcomes (A,B) and sample directly from that table.
<br>
Approach 2: Generate B first, then generate A using the appropriate conditional probability.
<br>
Here we can use the joint distribution approach, but if there were many assets, then this approach would have become very difficult.

# Observation
Observation 1: Both simulation approaches produce estimates that are very close to the theoretical values. The small differences are due to random sampling variability from using a finite sample size (n=10000).

Observation 2: The conditional simulation and the joint-probability simulation generate the same underlying dependence structure between LA and LB. Therefore, both methods converge to the same theoretical probabilities as the number of simulations increases.

Observation 3: The estimated joint loss probability is close to the theoretical value of 0.07, confirming that the positive dependence between the two assets has been correctly incorporated in the simulation.

Observation 4: The estimated values of E[N] and Var(N) are close to the theoretical values 0.30 and 0.35, validating the analytical calculations.

Observation 5: The joint-probability simulation happened to be slightly closer to the theoretical values in this particular run, but this is due to randomness and does not imply that one method is inherently more accurate than the other.
"""
